### ISSUE TITLE
typo in GitHub project description, "Miropython"

### ISSUE THREAD

**Issue by clach04** [de-dh/ESP32-Cheap-Yellow-Display-Micropython-LVGL#1]
"Miropython" instead of Micropython.

Thanks for making this project available, really handy to have links to pre built lvgl builds!

**Comment by de-dh** [comment]
Thank you, I corrected it.

Your welcome, getting the firmware was my main problem when I tried to work with the CYD.
I didn't succeed in compiling it and I thought that others may have the same problem.
The I found Stefan's Blog and with his instructions i finally got it running.
I posted the direct links for non-geman users.

**Comment by de-dh** [comment]
Closed
