### ISSUE TITLE
no need for changes to ILI9341 init method

### ISSUE THREAD

**Issue by clach04** [de-dh/ESP32-Cheap-Yellow-Display-Micropython-LVGL#2]
NOTE on my device color reproduction is improved with OUT changes in ILI9341 init method, instead pass in gamma=False

I.e. changes https://github.com/de-dh/ESP32-Cheap-Yellow-Display-Micropython-LVGL/blob/40a4dab2577e892ca00f5b90325a0ff509fa4563/demo_no_lvgl/ili9341.py#L175 should not be needed.

https://github.com/clach04/cyd_clocks/blob/main/01-rainbow-test.py is how I came to this conclusion. Note I do not have any kind of color measuring / correction equipment, just a phone and my eyes so my conclusion may be flawed! 😉

**Comment by clach04** [comment]
I didn't try experimenting with https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/cyd.md#the-display-doesnt-look-as-good

**Comment by de-dh** [comment]
Thank you, I will add this.

I didn't do much testing without LVGL since I wanted to create GUIs.
